// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBScv8c77L4-mvEHXECdKBfz0uBr-Ru9CE',
    appId: '1:455411552050:web:76df212702f6b5f2a6d12b',
    messagingSenderId: '455411552050',
    projectId: 'dapuratik-388fb',
    authDomain: 'dapuratik-388fb.firebaseapp.com',
    storageBucket: 'dapuratik-388fb.firebasestorage.app',
    measurementId: 'G-2EMYNJ76WT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9q6GrT0dY1s0gJ4hNG_5RfakqydZ71Ao',
    appId: '1:455411552050:android:929233e5481ed4f3a6d12b',
    messagingSenderId: '455411552050',
    projectId: 'dapuratik-388fb',
    storageBucket: 'dapuratik-388fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE_-yP2YqmAfsjuHIjA2ledeBcIiLBLh0',
    appId: '1:455411552050:ios:0bb564d116c6868fa6d12b',
    messagingSenderId: '455411552050',
    projectId: 'dapuratik-388fb',
    storageBucket: 'dapuratik-388fb.firebasestorage.app',
    iosBundleId: 'com.example.dapurAtik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE_-yP2YqmAfsjuHIjA2ledeBcIiLBLh0',
    appId: '1:455411552050:ios:0bb564d116c6868fa6d12b',
    messagingSenderId: '455411552050',
    projectId: 'dapuratik-388fb',
    storageBucket: 'dapuratik-388fb.firebasestorage.app',
    iosBundleId: 'com.example.dapurAtik',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBScv8c77L4-mvEHXECdKBfz0uBr-Ru9CE',
    appId: '1:455411552050:web:e4291e240e78c821a6d12b',
    messagingSenderId: '455411552050',
    projectId: 'dapuratik-388fb',
    authDomain: 'dapuratik-388fb.firebaseapp.com',
    storageBucket: 'dapuratik-388fb.firebasestorage.app',
    measurementId: 'G-GB4K2ED5YN',
  );
}
